<?php
/**
 * Template Name: nutrition facts Page
 *
 * @package CodesClue
 */
get_header(); ?>

    <main class="main">


<section class="hero-section-cus py-5">
  <div class="container">
    <div class="row align-items-center g-5">

      <div class="col-lg-6 text-center text-lg-start">
        <h1 class="hero-title">
         USDA & FDA-Compliant Nutrition Facts Labels — Built for Scale.
        </h1>
        <p class="hero-desc mt-3">
           A robust SaaS platform developed by CodesClue that helps food brands generate
  accurate, regulation-ready Nutrition Facts labels in minutes — without costly lab testing.
        </p>

        
      </div>

      <div class="col-lg-6">
        <img src="<?php echo get_template_directory_uri(); ?>/assets/images/portfolio-img/nutrition-facts/nutrition-hero.png" class="img-fluid" alt="image">
      </div>

    </div>
  </div>
</section>

<!-- =====================================================
SECTION 2: TRUSTED / STATS
===================================================== -->
<section class="stats-section py-5 border-top border-bottom">
  <div class="container">
    <p class="text-center stats-label mb-4">
       A compliance-focused food labeling platform engineered by CodesClue
    </p>

    <div class="row g-4 text-center">
      <div class="col-md-4">
        <div class="stat-card">
          <div class="stat-number">5,000+</div>
          <div class="stat-text">Food Businesses Supported</div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="stat-card">
          <div class="stat-number">10M+</div>
          <div class="stat-text">Nutrition Labels Generated</div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="stat-card">
          <div class="stat-number text-primary-custom">100%</div>
          <div class="stat-text">Regulation-Ready Accuracy</div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- =====================================================
SECTION 3: WHAT ARE NUTRITION FACTS
===================================================== -->
<section class="info-section py-5">
  <div class="container">
    <div class="section-head mb-5">
      <h2 class="section-title">About the Project</h2>
      <p class="section-desc">
        FreeFoodLabels is a specialized SaaS platform designed to simplify USDA and FDA-compliant
  nutrition labeling for packaged food products. CodesClue engineered the system to eliminate
  manual calculations and compliance risks through automation.
      </p>
    </div>

    <div class="row g-4">
      <div class="col-md-4">
        <div class="info-card">
          <div class="icon-circle">
            <i class="fa fa-shield-alt"></i>
          </div>
          <h5>Regulatory Compliance</h5>
          <p> Designed to meet USDA and FDA nutrition labeling requirements for packaged food products.</p>
        </div>
      </div>

      <div class="col-md-4">
        <div class="info-card">
          <div class="icon-circle">
            <i class="fa fa-file-alt"></i>
          </div>
          <h5>Consumer Transparency</h5>
          <p>Generates standardized Nutrition Facts panels that help brands maintain consumer trust.</p>
        </div>
      </div>

      <div class="col-md-4">
        <div class="info-card">
          <div class="icon-circle">
            <i class="fa fa-clipboard-check"></i>
          </div>
          <h5>Food Safety Assurance</h5>
          <p> Clearly highlights allergens and mandatory nutritional disclosures.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- =====================================================
SECTION 4: ANATOMY OF A NUTRITION LABEL
===================================================== -->
<section class="anatomy-section py-5 border-top border-bottom">
  <div class="container">
    <div class=" mb-5">
      <h2 class="section-title">What the Platform Generates</h2>
      <p class="section-desc"> Every Nutrition Facts label generated by the system follows official USDA and FDA formatting
  and calculation rules.
      </p>
    </div>

    <div class="row g-4">
      <div class="col-md-4">
        <div class="anatomy-item">
          <i class="fa fa-calculator icon-size-cus"></i>
          <h6 class="h6-cus">Serving Size Logic</h6>
          <p>Standardized serving size calculations based on regulatory guidelines.</p>
        </div>
      </div>

      <div class="col-md-4">
        <div class="anatomy-item">
          <i class="fa fa-fire icon-size-cus"></i>
          <h6 class="h6-cus">Calorie Calculation</h6>
          <p>Automated energy values derived from ingredient composition.</p>
        </div>
      </div>

      <div class="col-md-4">
        <div class="anatomy-item">
          <i class="fa-solid fa-chart-pie icon-size-cus"></i>
          <h6 class="h6-cus">Macronutrients</h6>
          <p>Accurate fat, carbohydrate, protein, and sodium breakdown.</p>
        </div>
      </div>

      <div class="col-md-4">
        <div class="anatomy-item">
          <i class="fa fa-leaf icon-size-cus"></i>
          <h6 class="h6-cus">Vitamins & Minerals</h6>
          <p>Displays mandatory micronutrients such as Vitamin D and Calcium.</p>
        </div>
      </div>

      <div class="col-md-4">
        <div class="anatomy-item">
          <i class="fa fa-percentage icon-size-cus"></i>
          <h6 class="h6-cus">Daily Value (%DV)</h6>
          <p>Correct %DV calculations using FDA-approved reference values.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- =====================================================
SECTION 5: HOW IT WORKS
===================================================== -->
<section class="how-section py-5">
  <div class="container">
    <div class="mb-5">
      <h2 class="section-title">End-to-End Label Automation</h2>
      <p class="section-desc">The platform converts recipe data into compliant nutrition labels through a fully automated workflow.</p>
    </div>

    <div class="row g-4 text-center">
      <div class="col">
        <div class="step-card active">
          <div class="step-circle">1</div>
          <h6>Add Ingredients</h6>
        </div>
      </div>
      <div class="col">
        <div class="step-card">
          <div class="step-circle ">2</div>
          <h6>Define Serving Size</h6>
        </div>
      </div>
      <div class="col">
        <div class="step-card">
          <div class="step-circle ">3</div>
          <h6>Automated Calculations</h6>
        </div>
      </div>
      <div class="col">
        <div class="step-card">
          <div class="step-circle ">4</div>
          <h6>Generate Label</h6>
        </div>
      </div>
      <div class="col">
        <div class="step-card">
          <div class="step-circle">5</div>
          <h6>Download & Use</h6>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- =====================================================
SECTION 6: KEY FEATURES
===================================================== -->
<section class="features-section py-5 border-top">
  <div class="container">
    <div class="mb-5">
      <h2 class="section-title">Key Features Delivered by CodesClue</h2>
      <p class="section-desc">
        A compliance-first feature set built for food brands, manufacturers, and enterprises.
      </p>
    </div>

    <div class="row g-4">
      <div class="col-md-4">
        <div class="feature-card">
          <i class="fa-solid fa-calculator icon-size-cus"></i>
          <h5>USDA-Compliant Calculations</h5>
          <p>Nutrition values calculated using official USDA FoodData Central sources.</p>
        </div>
      </div>

      <div class="col-md-4">
        <div class="feature-card">
          <i class="fa-solid fa-triangle-exclamation icon-size-cus"></i>
          <h5>Automated Allergen Detection</h5>
          <p>Identifies common allergens to reduce food safety risks.</p>
        </div>
      </div>

      <div class="col-md-4">
        <div class="feature-card">
          <i class="fa-solid fa-chart-line icon-size-cus"></i>
          <h5>Dynamic % Daily Value</h5>
          <p>Real-time %DV calculations based on regulatory standards.</p>
        </div>
      </div>

      <div class="col-md-4">
        <div class="feature-card">
          <i class="fa-solid fa-file-pen icon-size-cus"></i>
          <h5>Editable Label Builder</h5>
          <p>Customize labels while preserving compliance requirements.</p>
        </div>
      </div>

      <div class="col-md-4">
        <div class="feature-card">
          <i class="fa-solid fa-print icon-size-cus"></i>
          <h5>Print-Ready Outputs</h5>
          <p>Export labels in professional, audit-ready formats.</p>
        </div>
      </div>

      <div class="col-md-4">
        <div class="feature-card">
          <i class="fa-solid fa-cloud icon-size-cus"></i>
          <h5>Cloud Recipe Management</h5>
          <p>Securely manage recipes, revisions, and label history.</p>
        </div>
      </div>
    </div>
  </div>
</section>



<!-- =====================================================
SECTION 8: TRUST & COMPLIANCE
===================================================== -->
<section class="trust-section py-5 border-top">
  <div class="container">
    <div class="row align-items-center g-5">

      <div class="col-lg-6">
        <div class="badge-pill mb-3">
         Compliance-First Architecture
        </div>

        <h2 class="section-title">
          Built for Accuracy, Audits & Scale
        </h2>

        <p class="section-desc">
          The platform is continuously aligned with the latest USDA updates and FDA nutrition labeling rules.
        </p>

        <ul class="trust-list">
          <li class="align-items-center"><i class="fa-solid fa-circle-check"></i> USDA & FDA Regulation Alignment</li>
          <li class="align-items-center"><i class="fa-solid fa-circle-check"></i> Accurate Rounding & Formatting Rules</li>
          <li class="align-items-center"><i class="fa-solid fa-circle-check"></i> Mandatory Footnotes & Disclosures</li>
          <li class="align-items-center"><i class="fa-solid fa-circle-check"></i> Secure Cloud-Based Architecture</li>
        </ul>
      </div>

      <div class="col-lg-6 text-center">
        <img src="<?php echo get_template_directory_uri(); ?>/assets/images/portfolio-img/nutrition-facts/nutrition-facts-sec.png" class="img-fluid" alt="image">
      </div>

    </div>
  </div>
</section>



<!-- =====================================================
SECTION 10: FINAL CTA
===================================================== -->
<section class="cta-section py-5">
  <div class="container">
    <div class="cta-box text-center">
      <h2>
       A Compliance-Driven SaaS Product Built by CodesClue
      </h2>
      <p class="py-4">
       This project showcases our expertise in building regulation-ready platforms for food,
  healthcare, and enterprise industries.
      </p>

      <div class="d-flex justify-content-center gap-3 flex-wrap">
        <button class="btn btn-primary-custom btn-lg">
          View Live Product
        </button>
        <button class="btn btn-outline-light btn-lg">
          Talk to CodesClue
        </button>
      </div>
    </div>
  </div>
</section>



    </main>

<?php get_footer(); ?>